### ISSUE TITLE
Quicksearch

### ISSUE THREAD

**Issue by AndreHaupt85** [AndreHaupt85/capstone-project#11]
As a user
I need quick useable searchbar
to be able to have access to the cocktaildatabase

![Quicksearch](https://user-images.githubusercontent.com/109967968/194485823-3e7d154e-a187-4557-9fda-3ea94b7553f6.jpg)
xt

Acceptance Criteria
- [ ] full text search of all cocktail names in the database
- [ ] a results page

**Tasks**
 - [ ] adding searchbar on mainpage
 - [ ] adding resultspage
 - [ ] creating a search function

**Comment by deki84** [comment]
Looks good. That xt up there must be something that doesn't belong there? !You forgot to press the button?
