### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by AndreHaupt85** [AndreHaupt85/capstone-project#12]
As a ...user
I need a detailed search
to be able to search for special criterias in the database

**Description**
![Search](https://user-images.githubusercontent.com/109967968/194487262-9dfb3f53-b8b4-4836-a81d-43e7c94f6ac9.jpg)

Acceptance Criteria
- [ ] possibility to search for names, alcoholic and non alcoholic drinks, types of drinks

**Tasks**
 - [ ] add a new search page
 - [ ] use and expend the quicksearch function
