### ISSUE TITLE
Ingredience library

### ISSUE THREAD

**Issue by AndreHaupt85** [AndreHaupt85/capstone-project#14]
As a user
I need library page with alle the Spirits/ Fillers/ Decorations and Modifyers in the Database
tobe able to get a overview of all the ingredience.

**Description**
![Fillers](https://user-images.githubusercontent.com/109967968/194491459-e5a99e73-4e00-4ec2-8413-a26280496935.jpg)
![ingredients](https://user-images.githubusercontent.com/109967968/194491469-9b8d145d-c364-4e73-a288-8acae2643a73.jpg)
![Liqours](https://user-images.githubusercontent.com/109967968/194491480-d36c328a-ac6e-4ba9-a116-65c8eca16b06.jpg)
![Modifyers](https://user-images.githubusercontent.com/109967968/194491483-adcdcd16-5200-45fa-a963-f1c5fc022661.jpg)

Acceptance Criteria
- [ ] 4 Single Library Pages are created to display the ingrediences

**Tasks**
 - [ ] create 4 single Librarypages for Filler, Modifier, Decoration and Ingredience
 - [ ] add a map function on any page to display the informations out of the database

**Comment by deki84** [comment]
looks good.
