### ISSUE TITLE
Add Page

### ISSUE THREAD

**Issue by AndreHaupt85** [AndreHaupt85/capstone-project#15]
As a user
I need add-page
to be able to add my own cocktail recipes to the database

**Description**
![Add to Libary](https://user-images.githubusercontent.com/109967968/194497226-a753d6d6-4d67-4854-98d8-81db6ed8da3f.jpg)

Acceptance Criteria
- [ ] possible to add a name
- [ ] possible to add a recipe details
- [ ] possible to save the cocktail
- [ ] possible to use the captcha to approve your a human

**Tasks**
 - [ ] create a add page
 - [ ] create a form 
 - [ ] create a name input
 - [ ] create a components input with a dropdown menu for the components and a amount dropdown
 - [ ] creating a captcha for human check
 - [ ] create a destination where the cocktail is send to
