### ISSUE TITLE
Mainpage Gallery

### ISSUE THREAD

**Issue by AndreHaupt85** [AndreHaupt85/capstone-project#19]
**Value Proposition**
As a user
I need a gallery to be able to get inspiration new cocktails

**Description**
![Mainpage](https://user-images.githubusercontent.com/109967968/194748635-6394bafd-69b7-4b68-bf0c-010a4c9a96a8.jpg)

Acceptance Criteria
- [ ] there is a automatic sideways scrolling gallery with all cocktails in the database

**Tasks**
 - [ ] add a component to the main page that renders all cocktails of the database
 - [ ] make it sideways scrollable
 - [ ] make the scrolling automated
