### ISSUE TITLE
First Userstory

### ISSUE THREAD

**Issue by AndreHaupt85** [AndreHaupt85/capstone-project#2]
**Value Proposition**
As a 
 user
I need 
 first user interface
to be able to 
 realize what the app is made for.

**Description**
![scribble-1](https://user-images.githubusercontent.com/109967968/191211910-d0b67116-cb60-4655-80bd-3c8568f7385d.png)

Acceptance Criteria
- [ ] User can see the header
- [ ] user can see the first cocktail
- [ ] Adding a DummySeach

**Tasks**
 - [ ] adding a header
 - [ ] adding a H1
 - [ ] adding a json with the first cocktail
 - [ ]  link the json with the first cocktail on the page
 - [ ] Adding a Form with a Input Field

**Comment by NikRoe** [comment]
looks good to me! :)

Is the first cocktail that is displayed genuinely random? Otherwise, it would suffice to say: "the first cocktail is being displayed"

apart from that: nice work!!
