### ISSUE TITLE
Menubar

### ISSUE THREAD

**Issue by AndreHaupt85** [AndreHaupt85/capstone-project#3]
**Value Proposition**
As a 
 User
I need 
 a Menu
to be able to
 navigate between the different pages.

**Description**
![menu](https://user-images.githubusercontent.com/109967968/191232630-784af50e-2e4f-489e-b583-cb69ab065319.png)

Acceptance Criteria
 - [ ] when you click on the burger button the menu opens
 - [ ] when you click on library the library page opens
 - [ ] when you klick somewhere else in the menu nothing happens
 - [ ] when you click on the main page area the menu closes

**Tasks**
 - [ ] create a second page as library 
 - [ ] adding a burger menu button
 - [ ] adding a menu with 1 link to the library page

**Comment by ostermann-felix** [comment]
I can not find the burgermenu button at the scetch. Rest looks good to me.

**Comment by DanielGennat** [comment]
Hi Andre :)
- make it more profesional and write "you" :)
- tasks: add a link back to the main menu
