### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by AndreHaupt85** [AndreHaupt85/capstone-project#4]
**Value Proposition**
As a
 user
I need
 detail page
to be able to
 to get more informations about the selected drink

**Description**
![detailpage](https://user-images.githubusercontent.com/109967968/191245106-fdf9d30d-ceff-4485-b069-000492203459.png)

Acceptance Criteria
 - [ ] clicking in the library on the cocktail a detail page is opening
 - [ ] clicking on the burger menu the menu opens
 - [ ] clicking on mainpage or library the page changes
 - [ ] by clicking on the "back" button u will be guided to the whole library

**Tasks**
 - [ ] adding a detail page
 - [ ] link the cocktail in the DB with the library page
 - [ ] display all informations from the selected cocktail on the detail page
 - [ ] adding a "back" button that leads to the library
