### ISSUE TITLE
Adding content

### ISSUE THREAD

**Issue by AndreHaupt85** [AndreHaupt85/capstone-project#5]
**Value Proposition**
As a
 user
I need 
 backend content
to be able to
 get access to more cocktail informations

**Description**
<img width="260" alt="library" src="https://user-images.githubusercontent.com/109967968/191247234-bf0412ca-3ea3-41d7-b929-d2f5b810c6ff.png">

Acceptance Criteria
- [ ] more cocktails are visible in the library
- [ ] more possible detailed cocktails are shown

**Tasks**
 - [ ] extend the DB file by more cocktails
 - [ ] linking more cocktails on the library page
 - [ ] linking more cocktails to the detail page
